import { NextRequest, NextResponse } from "next/server";
import { getServerAuth } from "@/auth";
import { GoogleGenerativeAI } from "@google/generative-ai";

interface SpotifyArtist {
	name: string;
}

interface Song {
	title: string;
	artist: string;
}

type GeminiResponse = Array<Song>;

interface TrackData {
	title: string;
	artist: string;
	previewUrl: string | null;
	spotifyId: string | null;
}

interface Playlist {
	id: string;
	name: string;
	description: string;
	public: boolean;
	imageUrl: string;
	externalUrl: string;
	tracks: Array<{
		id: string;
		title: string;
		artist: string;
		previewUrl: string | null;
		spotifyId: string | null;
	}>;
	verificationStats: {
		totalGenerated: number;
		verifiedOnSpotify: number;
		unverified: number;
	};
}

interface GenerateRequestBody {
	prompt: string;
	title?: string;
	description?: string;
	numSongs?: number;
	isPublic?: boolean;
	language?: string;
	genre?: string;
	timePeriod?: string;
}

async function verifySongOnSpotify(
	title: string,
	artist: string
): Promise<{ spotifyId: string | null; previewUrl: string | null }> {
	const apiKey = process.env.GOOGLE_SEARCH_API_KEY;
	const engineId = process.env.GOOGLE_SEARCH_ENGINE_ID;

	if (!apiKey || !engineId) {
		return { spotifyId: null, previewUrl: null };
	}

	try {
		const query = `${title} ${artist} site:open.spotify.com/track`;
		const url = `https://www.googleapis.com/customsearch/v1?key=${apiKey}&cx=${engineId}&q=${encodeURIComponent(query)}`;

		const response = await fetch(url);
		if (!response.ok) return { spotifyId: null, previewUrl: null };

		const data = await response.json();
		const items = data.items || [];

		for (const item of items) {
			const link = item.link || "";
			const match = link.match(/\/track\/([a-zA-Z0-9]+)/);
			if (match) {
				return { spotifyId: match[1], previewUrl: null };
			}
		}
	} catch (error) {
		console.error("Spotify verification error:", error);
	}

	return { spotifyId: null, previewUrl: null };
}

function buildMock(title: string, description: string, tracks: TrackData[]): Playlist {
	const id = `mock-${Date.now()}`;
	return {
		id,
		name: title,
		description,
		public: true,
		imageUrl: "",
		externalUrl: "",
		tracks: tracks.map((track, idx) => ({
			id: `track-${idx}`,
			title: track.title,
			artist: track.artist,
			previewUrl: track.previewUrl,
			spotifyId: track.spotifyId,
		})),
		verificationStats: {
			totalGenerated: tracks.length,
			verifiedOnSpotify: tracks.filter((t) => t.spotifyId !== null).length,
			unverified: tracks.filter((t) => t.spotifyId === null).length,
		},
	};
}

export async function POST(request: NextRequest) {
	try {
		const session = await getServerAuth();
		if (!session) {
			return NextResponse.json(
				{ error: "Unauthorized" },
				{ status: 401 }
			);
		}

		const body = (await request.json()) as GenerateRequestBody;
		const {
			prompt,
			title = "My SonifyAI Playlist",
			description = "Generated by SonifyAI",
			numSongs = 15,
			language = "hollywood",
			genre = "",
			timePeriod = "",
		} = body;

		if (!prompt) {
			return NextResponse.json(
				{ error: "Prompt is required" },
				{ status: 400 }
			);
		}

		const geminiApiKey = process.env.GEMINI_API_KEY;
		if (!geminiApiKey) {
			return NextResponse.json(
				{ error: "Gemini API key not configured" },
				{ status: 500 }
			);
		}

		const genAI = new GoogleGenerativeAI(geminiApiKey);
		const model = genAI.getGenerativeModel({ model: "gemini-pro" });

		const languageContext = language !== "hollywood" ? `Focus on ${language} music. ` : "";
		const genreContext = genre ? `Genre: ${genre}. ` : "";
		const timeContext = timePeriod ? `Time period: ${timePeriod}. ` : "";

		const promptText = `Generate a playlist of ${numSongs} songs based on this mood: "${prompt}". ${languageContext}${genreContext}${timeContext}Return ONLY a JSON array of objects with "title" and "artist" fields. Example: [{"title": "Song Name", "artist": "Artist Name"}]`;

		const result = await model.generateContent(promptText);
		const response = await result.response;
		const text = response.text();

		let parsed: GeminiResponse;
		try {
			const jsonMatch = text.match(/\[[\s\S]*\]/);
			if (!jsonMatch) {
				throw new Error("No JSON array found in response");
			}
			parsed = JSON.parse(jsonMatch[0]) as GeminiResponse;
		} catch (error) {
			console.error("Failed to parse Gemini response:", error);
			return NextResponse.json(
				{ error: "Failed to parse AI response" },
				{ status: 500 }
			);
		}

		const tracks: TrackData[] = [];
		for (const song of parsed) {
			const verification = await verifySongOnSpotify(song.title, song.artist);
			tracks.push({
				title: song.title,
				artist: song.artist,
				previewUrl: verification.previewUrl,
				spotifyId: verification.spotifyId,
			});
		}

		const playlist = buildMock(title, description, tracks);

		return NextResponse.json({
			success: true,
			playlist,
		});
	} catch (error) {
		console.error("Generate error:", error);
		const errorMessage = error instanceof Error ? error.message : "Internal server error";
		return NextResponse.json(
			{ error: errorMessage },
			{ status: 500 }
		);
	}
}
